### ISSUE TITLE
Error when trying to fetch using file:// 

### ISSUE THREAD

**Issue by Regular-Baf** [packwiz/packwiz-installer#20]
# Using the command below, I get this error.
```java -jar packwiz-installer-bootstrap.jar file://wa/pack.toml```
![image](https://user-images.githubusercontent.com/95348524/163058338-9b071286-1043-43c4-91ba-2f7f178737c3.png)
## Here's the terminal output.
```Current version is: v0.3.3
New version is: v0.3.3
Already up to date!
Loading manifest file...
Loading pack file...
[FATAL] Failed to download pack.toml: 
java.lang.IllegalArgumentException: URI has an authority component
        at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:54)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:102)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at java.base/java.nio.file.Paths.get(Paths.java:98)
        at link.infra.packwiz.installer.request.handlers.RequestHandlerFile.getFileSource(RequestHandlerFile.kt:15)
        at link.infra.packwiz.installer.request.HandlerManager.getFileSource(HandlerManager.kt:43)
        at link.infra.packwiz.installer.UpdateManager.start(UpdateManager.kt:134)
        at link.infra.packwiz.installer.UpdateManager.<init>(UpdateManager.kt:43)
        at link.infra.packwiz.installer.Main.startup(Main.kt:81)
        at link.infra.packwiz.installer.Main.<init>(Main.kt:115)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
        at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
        at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
        at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
User selected to quit, exiting with code 1...```

**Comment by comp500** [comment]
I do want to support file paths directly (without going through Java URIs) in the future, though I'm not entirely decided on what the CLI syntax should be for it. Bafwiz-Updater looks nice :)
