### ISSUE TITLE
Installer crashes, failed to process index file

### ISSUE THREAD

**Issue by goldenapple3** [packwiz/packwiz-installer#39]
I believe that has to do with my [index.toml](https://appl.garden/mc/ariadne/packwiz/index.toml) containing paths with /c/
```
"/usr/lib/jvm/java-18-openjdk/bin/java" -jar packwiz-installer-bootstrap.jar https://appl.garden/mc/ariadne/packwiz/pack.toml
Current version is: null
New version is: v0.5.0
Attempting to update...
Update successful!
Loading manifest file...
Loading pack file...
Loading MultiMC pack file...
Loaded MultiMC config
Checking local files...
Modpack name: Ariadne
[FATAL] Failed to process index file: 
java.lang.StringIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.lang.String.checkIndex(String.java:4557)
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
	at java.base/java.lang.String.charAt(String.java:1515)
	at link.infra.packwiz.installer.target.path.PackwizPath.<init>(SourceFile:47)
	at link.infra.packwiz.installer.target.path.HttpUrlPath.<init>(SourceFile:10)
	at link.infra.packwiz.installer.target.path.HttpUrlPath.construct(SourceFile:43)
	at link.infra.packwiz.installer.target.path.HttpUrlPath.construct(SourceFile:10)
	at link.infra.packwiz.installer.target.path.PackwizPath.resolve(SourceFile:81)
	at link.infra.packwiz.installer.target.path.PackwizPath$Companion$mapperRelativeTo$lambda-2$$inlined$decoder$1.invoke(SourceFile:223)
	at link.infra.packwiz.installer.target.path.PackwizPath$Companion$mapperRelativeTo$lambda-2$$inlined$decoder$1.invoke(SourceFile:178)
	at link.infra.packwiz.installer.target.path.PackwizPath$Companion$mapperRelativeTo$lambda-2$$inlined$decoder$2.invoke(SourceFile:153)
	at link.infra.packwiz.installer.target.path.PackwizPath$Companion$mapperRelativeTo$lambda-2$$inlined$decoder$2.invoke(SourceFile:149)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:48)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:45)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:72)
	at cc.ekblad.toml.TomlMapper.decode(SourceFile:69)
	at link.infra.packwiz.installer.metadata.IndexFile$File$Companion$mapper$lambda-0$$inlined$delegateTransitive$4.invoke(SourceFile:224)
	at link.infra.packwiz.installer.metadata.IndexFile$File$Companion$mapper$lambda-0$$inlined$delegateTransitive$4.invoke(SourceFile:178)
	at link.infra.packwiz.installer.util._4KDelegationKt$delegateTransitive$$inlined$decoder$2.invoke(SourceFile:153)
	at link.infra.packwiz.installer.util._4KDelegationKt$delegateTransitive$$inlined$decoder$2.invoke(SourceFile:149)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:48)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:45)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:72)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toDataClass(SourceFile:172)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toObject(SourceFile:131)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:79)
	at cc.ekblad.toml.TomlMapper.decode(SourceFile:69)
	at link.infra.packwiz.installer.metadata.IndexFile$Companion$mapper$lambda-0$$inlined$delegateTransitive$4.invoke(SourceFile:224)
	at link.infra.packwiz.installer.metadata.IndexFile$Companion$mapper$lambda-0$$inlined$delegateTransitive$4.invoke(SourceFile:178)
	at link.infra.packwiz.installer.util._4KDelegationKt$delegateTransitive$$inlined$decoder$2.invoke(SourceFile:153)
	at link.infra.packwiz.installer.util._4KDelegationKt$delegateTransitive$$inlined$decoder$2.invoke(SourceFile:149)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:48)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:45)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:72)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decodeList(SourceFile:122)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toList(SourceFile:109)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:78)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toDataClass(SourceFile:172)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toObject(SourceFile:131)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:79)
	at cc.ekblad.toml.TomlMapper.decode(SourceFile:69)
	at link.infra.packwiz.installer.UpdateManager.processIndex(SourceFile:499)
	at link.infra.packwiz.installer.UpdateManager.start(SourceFile:174)
	at link.infra.packwiz.installer.UpdateManager.<init>(SourceFile:43)
	at link.infra.packwiz.installer.Main.startup(SourceFile:109)
	at link.infra.packwiz.installer.Main.<init>(SourceFile:144)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
	at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
	at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
User selected to quit, exiting with code 1...
```

**Comment by comp500** [comment]
Fixed by https://github.com/packwiz/packwiz-installer/commit/783e35cf73f7763f490b1e8a95804007f14fb67a :)

**Comment by goldenapple3** [comment]
Thanks!
