### ISSUE TITLE
Error when installing my pack

### ISSUE THREAD

**Issue by AliceDTRH** [packwiz/packwiz-installer#45]
```shell
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for 
	at okhttp3.HttpUrl$Builder.parse$okhttp(SourceFile:1261)
	at okhttp3.HttpUrl$Companion.get(SourceFile:1634)
	at link.infra.packwiz.installer.metadata.ModFile$Download$Companion$mapper$lambda-1$$inlined$decoder$1.invoke(SourceFile:223)
	at link.infra.packwiz.installer.metadata.ModFile$Download$Companion$mapper$lambda-1$$inlined$decoder$1.invoke(SourceFile:178)
	at link.infra.packwiz.installer.metadata.ModFile$Download$Companion$mapper$lambda-1$$inlined$decoder$2.invoke(SourceFile:153)
	at link.infra.packwiz.installer.metadata.ModFile$Download$Companion$mapper$lambda-1$$inlined$decoder$2.invoke(SourceFile:149)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:48)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:45)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:72)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toDataClass(SourceFile:172)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toObject(SourceFile:131)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:79)
	at cc.ekblad.toml.TomlMapper.decode(SourceFile:69)
	at link.infra.packwiz.installer.metadata.ModFile$Companion$mapper$lambda-1$$inlined$delegateTransitive$7.invoke(SourceFile:224)
	at link.infra.packwiz.installer.metadata.ModFile$Companion$mapper$lambda-1$$inlined$delegateTransitive$7.invoke(SourceFile:178)
	at link.infra.packwiz.installer.util._4KDelegationKt$delegateTransitive$$inlined$decoder$2.invoke(SourceFile:153)
	at link.infra.packwiz.installer.util._4KDelegationKt$delegateTransitive$$inlined$decoder$2.invoke(SourceFile:149)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:48)
	at cc.ekblad.toml.transcoding.TomlDecoder$decoderFor$1$1.invoke(SourceFile:45)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:72)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toDataClass(SourceFile:172)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.toObject(SourceFile:131)
	at cc.ekblad.toml.transcoding.TomlDecoderKt.decode(SourceFile:79)
	at cc.ekblad.toml.TomlMapper.decode(SourceFile:69)
	at link.infra.packwiz.installer.metadata.IndexFile$File.downloadMeta(SourceFile:99)
	at link.infra.packwiz.installer.DownloadTask.downloadMetadata(SourceFile:94)
	at link.infra.packwiz.installer.UpdateManager.processIndex$lambda-9(SourceFile:310)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
It seems to work fine otherwise. All mods are from curseforge.

**Comment by AliceDTRH** [comment]
You can find the pack config files at https://github.com/AliceDTRH/ShelterFromTheStormPackwiz

**Comment by comp500** [comment]
Does the error dialog say which file(s) caused this exception?

**Comment by AliceDTRH** [comment]
![image](https://user-images.githubusercontent.com/57547425/189125886-06c5126a-deef-44af-a0f2-bbd7be42eb0c.png)
I think all of them? But there's so many it's hard to say.

**Comment by comp500** [comment]
What's the `.index` [folder you have](https://github.com/AliceDTRH/ShelterFromTheStormPackwiz/tree/main/mods/.index)? This folder has `.pw.toml` files with `url = ""` (which I don't think should be valid, though the packwiz CLI might accept it).

**Comment by AliceDTRH** [comment]
Thank you for your response, I am sadly no longer using this software.
